// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Login3.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Login3")]
    public partial class Login3Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Login3.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Login3", "A short summary of the feature", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Successfull Login with Valid Credentials")]
        [NUnit.Framework.CategoryAttribute("Login_into_w3Schools")]
        [NUnit.Framework.TestCaseAttribute("abhishektupudana@gmail.com", "Cat1234@", new string[] {
                "source:Credentials.xlsx"}, Category="source:Credentials.xlsx")]
        [NUnit.Framework.TestCaseAttribute("ashishak760513@gmail.com", "mc*GWfTC6ui9.U", new string[] {
                "source:Credentials.xlsx"}, Category="source:Credentials.xlsx")]
        [NUnit.Framework.TestCaseAttribute("hkpk0721@gmail.com", "Qwerty@123", new string[] {
                "source:Credentials.xlsx"}, Category="source:Credentials.xlsx")]
        [NUnit.Framework.TestCaseAttribute("parweenroshni1998@gmail.com", "roshni@1998", new string[] {
                "source:Credentials.xlsx"}, Category="source:Credentials.xlsx")]
        [NUnit.Framework.TestCaseAttribute("mjanki1054@gmail.com", "@/#*J1@a0#N5$k4%I*", new string[] {
                "source:Credentials.xlsx"}, Category="source:Credentials.xlsx")]
        [NUnit.Framework.TestCaseAttribute("gauravranaji1998@gmail.com", "Mannu@12345", new string[] {
                "source:Credentials.xlsx"}, Category="source:Credentials.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sk1632766@gmail.com", "Sa12j09eet@#3", new string[] {
                "source:Credentials.xlsx"}, Category="source:Credentials.xlsx")]
        [NUnit.Framework.TestCaseAttribute("vk2plus2@gmail.com", "Firstps@1", new string[] {
                "source:Credentials.xlsx"}, Category="source:Credentials.xlsx")]
        [NUnit.Framework.TestCaseAttribute("tanushri1595@gmail.com", "Tanu@1234", new string[] {
                "source:Credentials.xlsx"}, Category="source:Credentials.xlsx")]
        [NUnit.Framework.TestCaseAttribute("kushagra.saurab2050@gmail.com", "NCTC@task1", new string[] {
                "source:Credentials.xlsx"}, Category="source:Credentials.xlsx")]
        public virtual void SuccessfullLoginWithValidCredentials(string userName, string password, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "Login_into_w3Schools"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Successfull Login with Valid Credentials", null, @__tags);
#line 6
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
 testRunner.Given("Navigate user to LogIn Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 8
 testRunner.When(string.Format("User enter UserName{0} and Password{1}", userName, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 9
 testRunner.And("Click on the LogIn button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 10
 testRunner.Then("Successful LogIN message should display", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
